=== Cassolette/Transformice-Electron/_release_schema-v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "jsonVersion": {
      "type": "integer",
      "description": "The internal JSON release version, used for compatibility checks."
    },
    "homepage": {
      "type":"string",
      "description": "The URL to the homepage."
    },
    "archLatest": {
      "type": "object",
      "description": "Lists the latest versions for the architectures.",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "description": "Properties for the architecture identifier.",
          "properties": {
            "stable": {
              "type": "string",
              "description": "Latest stable branch version for the architecture."
            }
          }
        }
      }
    },
    "urlSyntax": {
      "type": "object",
      "description": "The default syntax for all the release URL. This can be individually overriden in the meta with `overrideArchUrl`.",
      "patternProperties": {
        "^.*$": {
          "type": "string",
          "description": "The syntax for the architecture identifier."
        }
      }
    },
    "releaseMeta": {
      "type": "object",
      "description": "Lists metadata for the various releases.",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "description": "Properties for the release version identifier.",
          "properties": {
            "version": {
              "type": "string",
              "description": "The release version identifier."
            },
            "incrementalVersion": {
              "type": "integer",
              "description": "The incremental version identifier."
            },
            "type": {
              "type": "string",
              "description": "The release branch."
            },
            "overrideArchUrl": {
              "type": "object",
              "description": "The direct URL override for the architecture.",
              "patternProperties": {
                "^.*$": {
                  "type": "string",
                  "description": "The direct URL override for the architecture identifier."
                }
              }
            }
          },
          "required": ["version", "incrementalVersion", "type"]
        }
      }
    }
  },
  "required": ["jsonVersion", "archLatest", "urlSyntax", "releaseMeta"]
}

=== Cassolette/Transformice-Electron/release-v1.json
{
    "$schema": "./_release_schema-v1.json",
    "jsonVersion": 1,
    "homepage": "https://cassolette.github.io/Transformice-Electron/",
    "archLatest": {
        "windows": {
            "stable": "2.0.10"
        },
        "macos": {
            "stable": "2.0.10"
        },
        "linux": {
            "stable": "1.1.8"
        }
    },
    "urlSyntax": {
        "windows": "https://github.com/Cassolette/Transformice-Electron/releases/download/v{$version}/Transformice.Setup.{$version}.exe",
        "macos": "https://github.com/Cassolette/Transformice-Electron/releases/download/v{$version}/Transformice-{$version}.dmg"
    },
    "releaseMeta": {
        "2.0.10": {
            "version": "2.0.10",
            "incrementalVersion": 1000,
            "type": "stable"
        },
        "1.1.8": {
            "version": "1.1.8",
            "incrementalVersion": 100,
            "type": "stable",
            "overrideArchUrl": {
                "linux": "https://github.com/Cassolette/Transformice-Electron/releases/download/1.1.8/transformice-electron_1.1.8_amd64.snap"
            }
        }
    }
}
